### ISSUE TITLE
Missing bounds for `base` break builds with QuicckCheck-2.17.0.0 (and probably more)

### ISSUE THREAD

**Issue by ulysses4ever** [nick8325/quickcheck#438]
### [`getDown` was introduced in GHC 8.10](https://hackage.haskell.org/package/base-4.21.0.0/docs/Data-Ord.html#v:getDown) (base-4.14.0.0)

So, I'm getting

```
src/Test/QuickCheck/Arbitrary.hs:1181:32: error:
    Variable not in scope: getDown :: Down a -> a
```

[with GHC 8.8](https://github.com/ulysses4ever/rere/actions/runs/18313554511/job/52147775877) and [GHC 8.6](https://github.com/ulysses4ever/rere/actions/runs/18313554511/job/52147775911).

### [`Data.Finctor.Contravariant` was introduced in GHC 8.6](https://hackage.haskell.org/package/base-4.21.0.0/docs/Data-Functor-Contravariant.html) (base-4.12.0.0)

So, I'm getting

```
src/Test/QuickCheck/Arbitrary.hs:218:1: error:
    Could not find module ‘Data.Functor.Contravariant’
```

[with GHC 8.4](https://github.com/ulysses4ever/rere/actions/runs/18313554511/job/52147775897).

---

It will also bring problems down the road that `transformers`, `containers`, `data-array-byte`, `deepseq`, `template-haskell` are all missing (some) bounds. Also, `random` is outdated and uses an upper bound with trailing zeroes which is a bad idea, as rightly pointed out by `cabal check`.

All these issues could be fixed by a Hackage revision.
