### ISSUE TITLE
QuickCheck-2.8.1 won't compile with GHC 7.12.x

### ISSUE THREAD

**Issue by peti** [nick8325/quickcheck#59]
Citing from http://hydra.cryp.to/build/1054975/nixlog/1/raw:

~~~~~~~
Test/QuickCheck/All.hs:76:11: error:
    The constructor ‘ClassOpI’ should have 3 arguments, but has been given 4
    In the pattern: ClassOpI _ ty _ _
    In an equation for ‘infoType’: infoType (ClassOpI _ ty _ _) = ty
~~~~~~~

**Comment by nick8325** [comment]
Should be fixed now, thanks!

**Comment by peti** [comment]
Will you release a new version with that fix?
