### ISSUE TITLE
QuickCheck doesn't compile with ghc 9.0 alpha

### ISSUE THREAD

**Issue by GeorgeCo** [nick8325/quickcheck#318]
I know it's early but QuickCheck doesn't install against ghc 9.0. You may have to compile a couple of packages with --allow-new to get to this error:

Building library for QuickCheck-2.14.1..
...
[14 of 16] Compiling Test.QuickCheck.All ( src/Test/QuickCheck/All.hs, dist/build/Test/QuickCheck/All.o, dist/build/Test/QuickCheck/All.dyn_o )

src/Test/QuickCheck/All.hs:102:14: error:
    • The constructor ‘PlainTV’ should have 2 arguments, but has been given 1
    • In the pattern: PlainTV _
      In an equation for ‘plain’: plain (PlainTV _) = True
      In the expression:
        do let plain (PlainTV _) = True
               plain (KindedTV _ StarT) = True
               plain _ = False
           unless (all plain xs) $ err "Higher-kinded type variables in type"
           return (map (\ (PlainTV x) -> x) xs, ctx, ty)
    |
102 |   let plain (PlainTV  _)       = True
    |              ^^^^^^^^^^

src/Test/QuickCheck/All.hs:110:18: error:
    • The constructor ‘PlainTV’ should have 2 arguments, but has been given 1
    • In the pattern: PlainTV x
      In the first argument of ‘map’, namely ‘(\ (PlainTV x) -> x)’
      In the expression: map (\ (PlainTV x) -> x) xs
    |
110 |   return (map (\(PlainTV x) -> x) xs, ctx, ty)
    |                  ^^^^^^^^^
cabal: Failed to build QuickCheck-2.14.1. See the build log above for details.

**Comment by phadej** [comment]
See #314 (and also #298, #306).

**Comment by GeorgeCo** [comment]
It seems to compile now with 9.0 rc1,  i.e. version 9.0.0.20201227. Unfortunately I'm not sure if I used --allow-new on it or its dependencies.

**Comment by andreasabel** [comment]
This issue can be closed, 2.14.2 builds with ghc 9.0.1.
